name: Build Backend

on:
  - push

permissions:
  contents: read
  checks: write

jobs:
  build-backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build and test with Gradle
        run: ./gradlew build test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        # This step should be run even if the previous steps fail
        if: (success() || failure())
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
