name: Build Frontend

on:
  - push

permissions:
  contents: read

jobs:
  build-frontend:


    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './Frontend/package-lock.json'
      - name: Build and test with npm
        run: | 
          npm ci 
          npm run test:unit
